/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/api-bindings.d.ts` (hash: ed8d5f233a17a12cc0d91784e17402ed)
interface __BaseEnv_Env {
	OPENAPI_ASSETS: Fetcher;
	PUBLIC_API_ORIGIN: "https://api.dev.packetrove.com" | "https://api.staging.packetrove.com" | "https://api.packetrove.com";
	PUBLIC_WEBSITE_ORIGIN: "https://dev.packetrove.com" | "https://staging.packetrove.com" | "https://packetrove.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface DevelopmentEnv {
		OPENAPI_ASSETS: Fetcher;
		PUBLIC_API_ORIGIN: "https://api.dev.packetrove.com";
		PUBLIC_WEBSITE_ORIGIN: "https://dev.packetrove.com";
	}
	interface StagingEnv {
		OPENAPI_ASSETS: Fetcher;
		PUBLIC_API_ORIGIN: "https://api.staging.packetrove.com";
		PUBLIC_WEBSITE_ORIGIN: "https://staging.packetrove.com";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_API_ORIGIN" | "PUBLIC_WEBSITE_ORIGIN">> {}
}
