/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/api-bindings.d.ts` (hash: 51fdb900d8fd4ec72a4b5938a63ef526)
interface __BaseEnv_Env {
	OPENAPI_ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
