/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.website.jsonc --include-runtime=false --env-interface=WebsiteBindings src/website-bindings.d.ts` (hash: 85d597477bac79f3401a0840c9615632)
interface __BaseEnv_WebsiteBindings {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./website");
	}
	interface Env extends __BaseEnv_WebsiteBindings {}
}
interface WebsiteBindings extends __BaseEnv_WebsiteBindings {}
