export const feedbackCopy = {
  title: "Optionales Agentenfeedback",
  availability: "{{name}} ist eine optionale MCP-Supportfunktion und standardmäßig deaktiviert. Sie ist nur verfügbar, wenn tools/list sie aufführt, und sendet einen privaten Bericht zur manuellen Prüfung. Website, Web API und CLI bieten keine Einreichung.",
  authorization: "Nur auf Wunsch oder mit Zustimmung des Nutzers senden. Vorgelegte oder bereits genehmigte Berichte können direkt übermittelt werden. Neu formulierte Inhalte zuerst zur Genehmigung zeigen. Keine Gesprächsverläufe anhängen und nicht nach jedem Aufruf um Feedback bitten.",
  inputs: "category: bug, confusing_behavior oder feature_request. summary ist erforderlich; tool_name und synthetic_reproduction sind optional. Bugs benötigen expected und actual, unklares Verhalten actual. Featurewünsche erlauben expected, aber weder actual noch error_code. summary: {{summaryLimit}} Unicode-Codepunkte; expected/actual: je {{descriptionLimit}}; Reproduktion: {{reproductionLimit}}. Ein optionaler error_code verwendet Großbuchstaben. Unbekannte Felder werden abgelehnt; serialisierte Argumente dürfen 8 KiB nicht überschreiten.",
  limits: "Pro beobachteter Ausgangs-IP sind {{ipLimit}} angenommene Berichte in den letzten 24 Stunden erlaubt. Gemeinsam genutzte Ausgänge teilen das Kontingent. Zusätzlich gelten {{dailyLimit}} Berichte pro UTC-Kalendertag und {{reportLimit}} gespeicherte Berichte. Berechnungen und Abfragen bleiben davon unabhängig.",
  delivery: "Bei Erfolg werden accepted und receipt_id zurückgegeben, ohne Zusage einer Antwort oder Korrektur. Eine bestätigte Ablehnung enthält delivery: not_accepted. Nach Zeitüberschreitung, Abbruch oder DELIVERY_UNCERTAIN nicht automatisch wiederholen: Der Bericht kann bereits gespeichert sein. Es gibt keine Deduplizierung.",
  privacyTitle: "Freiwilliges Agentenfeedback",
  privacyBody: "Wenn aktiviert, speichert submit-feedback den genehmigten Bericht und die öffentliche Dienstversion in einer privaten Cloudflare-D1-Warteschlange zur manuellen Prüfung. Nur künstliche Beispiele verwenden; keine echten Netzwerkdaten, Zertifikate, Geheimnisse, Protokolle oder Gesprächsverläufe. Berichte verfallen nach 90 Tagen und werden stündlich gelöscht. Ein mit einem Schlüssel abgeleiteter IP-Marker und Annahmezeiten werden getrennt für das 24-Stunden-Kontingent gespeichert; abgelaufene Einträge werden stündlich entfernt. Sie erscheinen weder in Berichten noch in Logs. Eine Löschung gibt kein Kontingent zurück. D1-Wiederherstellungskopien können gelöschte Inhalte bis zu 30 weitere Tage enthalten. Löschwünsche mit der Empfangsbestätigung per E-Mail an den Maintainer senden. Berichte werden nicht automatisch veröffentlicht.",
} as const;
