export const feedbackCopy = {
  title: "Optionales Agentenfeedback",
  availability: "{{name}} ist eine optionale MCP-Supportoperation und standardmäßig deaktiviert. Nur verwenden, wenn tools/list sie anbietet. Sie sendet einen privaten Bericht per E-Mail zur manuellen Prüfung an den Maintainer; Website, Web API und CLI bieten keine Einreichung.",
  authorization: "Nur auf Wunsch oder mit Zustimmung des Nutzers senden. Vorgelegte oder bereits genehmigte Berichte können direkt übermittelt werden. Neu formulierte Inhalte zuerst zur Genehmigung zeigen. Keine Gesprächsverläufe anhängen und nicht nach jedem Aufruf um Feedback bitten.",
  inputs: "category: bug, confusing_behavior oder feature_request. summary ist erforderlich; tool_name und synthetic_reproduction sind optional. Bugs benötigen expected und actual, unklares Verhalten actual. Featurewünsche erlauben expected, aber weder actual noch error_code. summary: {{summaryLimit}} Unicode-Codepunkte; expected/actual: je {{descriptionLimit}}; Reproduktion: {{reproductionLimit}}. Ein optionaler error_code verwendet Großbuchstaben. Unbekannte Felder werden abgelehnt; serialisierte Argumente dürfen 8 KiB nicht überschreiten.",
  limits: "Die ungefähren Grenzen betragen {{ipLimit}} Einreichungen pro beobachteter Ausgangs-IP in den letzten 24 Stunden und {{dailyLimit}} pro UTC-Kalendertag für den gesamten Dienst. Gemeinsame Ausgänge teilen das Kontingent. Gleichzeitige Anfragen und die KV-Synchronisierung können beide Grenzen überschreiten. Ungewisse Sendungen oder fehlgeschlagene Freigaben belegen das Kontingent bis zum Ablauf. Berechnungen und Abfragen bleiben unabhängig.",
  delivery: "accepted und receipt_id bedeuten, dass der E-Mail-Dienst die Einreichung angenommen hat, nicht dass sie im Posteingang liegt oder gelesen wurde. Eine Antwort oder Korrektur wird nicht zugesagt. Bestätigte Ablehnungen enthalten delivery: not_accepted. Nach Zeitüberschreitung, Abbruch oder DELIVERY_UNCERTAIN nie automatisch erneut senden: Der Bericht kann bereits per E-Mail versandt sein. Es gibt keine Deduplizierung.",
  privacyTitle: "Freiwilliges Agentenfeedback",
  privacyBody: "Wenn aktiviert, sendet submit-feedback den genehmigten Bericht, die Empfangsbestätigung, die öffentliche Dienstversion und die Einreichungszeit über Cloudflare per E-Mail an den Maintainer zur manuellen Prüfung. Nur künstliche Beispiele verwenden; keine echten Netzwerkdaten, Zertifikate, Geheimnisse, Protokolle oder Gesprächsverläufe. Aufbewahrung und Löschung im Postfach erfolgen manuell; Berichte verfallen nicht automatisch. Cloudflare Workers KV speichert getrennt nur schlüsselbasierte Ausgangs-IP-Marker und Reservierungszeiten, die nach 24 Stunden ablaufen, ohne Berichtsinhalte oder Verknüpfung zur Empfangsbestätigung. Marker erscheinen weder in Berichten noch in Logs. Das Löschen einer E-Mail gibt kein Kontingent zurück. Löschwünsche mit der Empfangsbestätigung per E-Mail an den Maintainer senden. Berichte werden nicht automatisch veröffentlicht.",
} as const;
