export const feedbackCopy = {
  title: "Optional agent feedback",
  availability: "{{name}} is an optional MCP support operation, disabled by default. Use it only when tools/list advertises it. It emails a private report to the maintainer for human review; website, Web API, and CLI submissions are unavailable.",
  authorization: "Submit only when the user requests or authorizes feedback. A report they supplied or approved can be sent directly. Show any newly composed report for approval first. Never attach conversation history or solicit reports after every call.",
  inputs: "Choose category: bug, confusing_behavior, or feature_request. Provide summary and optionally tool_name or synthetic_reproduction. Bugs require expected and actual; confusing behavior requires actual. Feature requests may include expected, but not actual or error_code. Summary allows {{summaryLimit}} Unicode code points, expected/actual {{descriptionLimit}} each, and reproduction {{reproductionLimit}}. Optional error_code is an uppercase code. Unknown fields are rejected; serialized arguments must fit 8 KiB.",
  limits: "Approximate limits target {{ipLimit}} submissions per observed exit IP in the preceding 24 hours and {{dailyLimit}} submissions per UTC day across the service. Shared exits share quota. Concurrent requests and KV propagation can exceed either limit. Uncertain sends or failed quota releases occupy quota until expiry. Feedback limits do not affect calculations or lookups.",
  delivery: "Success returns accepted and receipt_id: the email service acknowledged submission, not inbox delivery or reading. No reply or fix is promised. Known rejection returns delivery: not_accepted. Never automatically resend after timeout, cancellation, or DELIVERY_UNCERTAIN: the report may already have been emailed. Reports are not deduplicated.",
  privacyTitle: "Voluntary agent feedback",
  privacyBody: "When enabled, submit-feedback sends your authorized report, receipt, public service version, and submission time by email through Cloudflare to the maintainer for human review. Use synthetic examples; exclude real network data, certificates, secrets, logs, and conversation history. Mailbox retention and deletion are managed manually; reports have no automatic expiry. Cloudflare Workers KV separately stores only keyed exit-IP markers and reservation times, expiring after 24 hours, without report bodies or receipt links. Markers are neither attached to reports nor logged. Deleting an email does not restore quota. Request deletion by emailing the maintainer with your receipt. Reports are not published automatically.",
} as const;
