export const feedbackCopy = {
  title: "Optional agent feedback",
  availability: "{{name}} is an optional MCP support operation, disabled by default. Use it only when tools/list advertises it. It sends a private report for human review; website, Web API, and CLI submissions are unavailable.",
  authorization: "Submit only when the user requests or authorizes feedback. A report they supplied or approved can be sent directly. Show any newly composed report for approval first. Never attach conversation history or solicit reports after every call.",
  inputs: "Choose category: bug, confusing_behavior, or feature_request. Provide summary and optionally tool_name or synthetic_reproduction. Bugs require expected and actual; confusing behavior requires actual. Feature requests may include expected, but not actual or error_code. Summary allows {{summaryLimit}} Unicode code points, expected/actual {{descriptionLimit}} each, and reproduction {{reproductionLimit}}. Optional error_code is an uppercase code. Unknown fields are rejected; serialized arguments must fit 8 KiB.",
  limits: "Each observed exit IP can submit {{ipLimit}} accepted reports in the preceding 24 hours. Shared exits share this quota. The service also limits acceptance to {{dailyLimit}} reports per UTC day and {{reportLimit}} stored reports. Feedback limits do not affect calculations or lookups.",
  delivery: "Success returns accepted and receipt_id, without a promised reply or fix. Known rejection returns delivery: not_accepted. Do not automatically retry timeouts, cancellation, or DELIVERY_UNCERTAIN: the report may already be stored. Reports are not deduplicated.",
  privacyTitle: "Voluntary agent feedback",
  privacyBody: "When enabled, submit-feedback stores your authorized report and the public service version in a private Cloudflare D1 queue for human review. Use synthetic examples; exclude real network data, certificates, secrets, logs, and conversation history. Reports expire after 90 days, with hourly deletion. A keyed exit-IP marker and acceptance times are stored separately for the preceding 24 hours, with hourly cleanup; neither is attached to reports or logged. Deleting a report does not restore quota. D1 recovery backups may retain deleted material for up to 30 additional days. Request deletion by emailing the maintainer with your receipt. Reports are not published automatically.",
} as const;
