export const feedbackCopy = {
  title: "Comentarios opcionales de agentes",
  availability: "{{name}} es una operación de soporte MCP opcional, desactivada por defecto. Úsala solo si aparece en tools/list. Envía un informe privado para revisión humana; el sitio web, Web API y CLI no permiten enviarlo.",
  authorization: "Envía comentarios solo a petición del usuario o con su autorización. Puedes enviar directamente un informe aportado o aprobado. Muestra primero cualquier texto nuevo para obtener aprobación. No adjuntes conversaciones ni solicites comentarios después de cada llamada.",
  inputs: "category: bug, confusing_behavior o feature_request. Incluye summary y, opcionalmente, tool_name o synthetic_reproduction. Los errores requieren expected y actual; el comportamiento confuso, actual. Las funciones propuestas admiten expected, pero no actual ni error_code. summary: {{summaryLimit}} puntos de código Unicode; expected/actual: {{descriptionLimit}} cada uno; reproducción: {{reproductionLimit}}. error_code opcional usa mayúsculas. Se rechazan campos desconocidos; los argumentos serializados no deben superar 8 KiB.",
  limits: "Cada IP de salida observada admite {{ipLimit}} informes aceptados en las últimas 24 horas. Las salidas compartidas comparten cuota. También se aplican {{dailyLimit}} informes por día UTC y {{reportLimit}} informes almacenados. Estos límites no afectan a cálculos ni consultas.",
  delivery: "El éxito devuelve accepted y receipt_id, sin prometer respuesta ni corrección. El rechazo confirmado devuelve delivery: not_accepted. No reintentes automáticamente tras un tiempo de espera, cancelación o DELIVERY_UNCERTAIN: el informe podría estar almacenado. No se eliminan duplicados.",
  privacyTitle: "Comentarios voluntarios de agentes",
  privacyBody: "Cuando está habilitado, submit-feedback guarda el informe autorizado y la versión pública del servicio en una cola privada de Cloudflare D1 para revisión humana. Usa ejemplos sintéticos; excluye datos de red reales, certificados, secretos, registros e historial de conversación. Los informes caducan a los 90 días y se eliminan cada hora. Una marca de la IP de salida derivada con clave y los tiempos de aceptación se guardan por separado para la cuota de las últimas 24 horas; los registros vencidos se limpian cada hora. No se adjuntan a informes ni se registran en logs. Borrar un informe no devuelve cuota. Las copias de recuperación D1 pueden conservar material eliminado hasta 30 días adicionales. Solicita su eliminación por correo al responsable con el recibo. Los informes no se publican automáticamente.",
} as const;
