export const feedbackCopy = {
  title: "Comentarios opcionales de agentes",
  availability: "{{name}} es una operación opcional de soporte MCP, desactivada por defecto. Úsala solo cuando tools/list la anuncie. Envía un informe privado por correo al responsable para revisión humana; no hay envío desde el sitio web, Web API ni CLI.",
  authorization: "Envía comentarios solo a petición del usuario o con su autorización. Puedes enviar directamente un informe aportado o aprobado. Muestra primero cualquier texto nuevo para obtener aprobación. No adjuntes conversaciones ni solicites comentarios después de cada llamada.",
  inputs: "category: bug, confusing_behavior o feature_request. Incluye summary y, opcionalmente, tool_name o synthetic_reproduction. Los errores requieren expected y actual; el comportamiento confuso, actual. Las funciones propuestas admiten expected, pero no actual ni error_code. summary: {{summaryLimit}} puntos de código Unicode; expected/actual: {{descriptionLimit}} cada uno; reproducción: {{reproductionLimit}}. error_code opcional usa mayúsculas. Se rechazan campos desconocidos; los argumentos serializados no deben superar 8 KiB.",
  limits: "Los límites aproximados son {{ipLimit}} envíos por IP de salida observada en las últimas 24 horas y {{dailyLimit}} por día UTC para todo el servicio. Las salidas compartidas comparten cuota. Las solicitudes concurrentes y la propagación de KV pueden superar ambos límites. Los envíos inciertos o las liberaciones fallidas ocupan cuota hasta caducar. Los cálculos y consultas no se ven afectados.",
  delivery: "accepted y receipt_id indican que el servicio de correo aceptó el envío, no que llegó a la bandeja de entrada o se leyó. No se promete respuesta ni solución. El rechazo confirmado devuelve delivery: not_accepted. Nunca reenvíes automáticamente tras un tiempo de espera, cancelación o DELIVERY_UNCERTAIN: el informe puede haberse enviado por correo. No hay deduplicación.",
  privacyTitle: "Comentarios voluntarios de agentes",
  privacyBody: "Al activarse, submit-feedback envía el informe autorizado, el recibo, la versión pública del servicio y la hora de envío por correo a través de Cloudflare al responsable para revisión humana. Usa ejemplos sintéticos; excluye datos reales de red, certificados, secretos, registros e historial de conversaciones. La conservación y eliminación en el buzón se gestionan manualmente; los informes no caducan automáticamente. Cloudflare Workers KV guarda por separado solo marcadores de IP de salida derivados con clave y horas de reserva, que caducan tras 24 horas, sin el contenido del informe ni vínculos al recibo. Los marcadores no se adjuntan a informes ni se registran. Eliminar un correo no restaura la cuota. Solicita la eliminación por correo al responsable con el recibo. Los informes no se publican automáticamente.",
} as const;
