export const feedbackCopy = {
  title: "Retours facultatifs des agents",
  availability: "{{name}} est une opération de support MCP facultative, désactivée par défaut. Utilisez-la seulement si tools/list la propose. Elle envoie un rapport privé par e-mail au responsable pour examen humain ; aucun envoi depuis le site, la Web API ou la CLI.",
  authorization: "Envoyez uniquement à la demande de l’utilisateur ou avec son accord. Un rapport fourni ou déjà approuvé peut être envoyé directement. Présentez tout nouveau texte pour approbation. Ne joignez pas l’historique des conversations et ne sollicitez pas un retour après chaque appel.",
  inputs: "category : bug, confusing_behavior ou feature_request. summary est requis ; tool_name et synthetic_reproduction sont facultatifs. Un bug exige expected et actual ; un comportement confus, actual. Une demande de fonctionnalité accepte expected, mais pas actual ni error_code. summary : {{summaryLimit}} points de code Unicode ; expected/actual : {{descriptionLimit}} chacun ; reproduction : {{reproductionLimit}}. error_code facultatif utilise des majuscules. Champs inconnus refusés ; arguments sérialisés limités à 8 KiB.",
  limits: "Les limites approximatives sont de {{ipLimit}} envois par IP de sortie observée sur les dernières 24 heures et de {{dailyLimit}} par jour UTC pour tout le service. Les sorties partagées partagent leur quota. Les requêtes simultanées et la propagation KV peuvent dépasser ces limites. Les envois incertains ou les libérations de quota échouées occupent le quota jusqu’à expiration. Les calculs et recherches restent indépendants.",
  delivery: "accepted et receipt_id indiquent que le service e-mail a accepté l’envoi, sans garantir son arrivée dans la boîte de réception ni sa lecture. Aucune réponse ou correction n’est promise. Un refus confirmé renvoie delivery: not_accepted. Ne renvoyez jamais automatiquement après un délai dépassé, une annulation ou DELIVERY_UNCERTAIN : le rapport peut déjà avoir été envoyé par e-mail. Il n’y a pas de déduplication.",
  privacyTitle: "Retours volontaires des agents",
  privacyBody: "Lorsqu’il est activé, submit-feedback transmet le rapport autorisé, le reçu, la version publique du service et l’heure d’envoi par e-mail via Cloudflare au responsable pour examen humain. Utilisez des exemples fictifs ; excluez données réseau réelles, certificats, secrets, journaux et historique de conversation. La conservation et la suppression dans la boîte mail sont gérées manuellement ; les rapports n’expirent pas automatiquement. Cloudflare Workers KV conserve séparément uniquement des marqueurs d’IP de sortie dérivés avec une clé et les heures de réservation, expirant après 24 heures, sans contenu du rapport ni lien avec le reçu. Les marqueurs ne figurent ni dans les rapports ni dans les journaux. Supprimer un e-mail ne restitue pas le quota. Demandez la suppression par e-mail au responsable avec votre reçu. Les rapports ne sont pas publiés automatiquement.",
} as const;
