export const feedbackCopy = {
  title: "Retours facultatifs des agents",
  availability: "{{name}} est une opération de support MCP facultative, désactivée par défaut. Utilisez-la uniquement si tools/list la présente. Elle envoie un rapport privé pour examen humain ; le site, Web API et CLI ne permettent pas cet envoi.",
  authorization: "Envoyez uniquement à la demande de l’utilisateur ou avec son accord. Un rapport fourni ou déjà approuvé peut être envoyé directement. Présentez tout nouveau texte pour approbation. Ne joignez pas l’historique des conversations et ne sollicitez pas un retour après chaque appel.",
  inputs: "category : bug, confusing_behavior ou feature_request. summary est requis ; tool_name et synthetic_reproduction sont facultatifs. Un bug exige expected et actual ; un comportement confus, actual. Une demande de fonctionnalité accepte expected, mais pas actual ni error_code. summary : {{summaryLimit}} points de code Unicode ; expected/actual : {{descriptionLimit}} chacun ; reproduction : {{reproductionLimit}}. error_code facultatif utilise des majuscules. Champs inconnus refusés ; arguments sérialisés limités à 8 KiB.",
  limits: "Chaque IP de sortie observée peut envoyer {{ipLimit}} rapports acceptés sur les dernières 24 heures. Les sorties partagées partagent ce quota. Limites supplémentaires : {{dailyLimit}} rapports par jour UTC et {{reportLimit}} rapports stockés. Les calculs et recherches restent indépendants.",
  delivery: "Le succès renvoie accepted et receipt_id, sans promesse de réponse ou de correction. Un refus certain indique delivery: not_accepted. Ne réessayez pas automatiquement après expiration du délai, annulation ou DELIVERY_UNCERTAIN : le rapport peut être stocké. Aucun dédoublonnage n’est effectué.",
  privacyTitle: "Retours volontaires des agents",
  privacyBody: "Lorsqu’il est activé, submit-feedback conserve le rapport autorisé et la version publique du service dans une file privée Cloudflare D1 pour examen humain. Utilisez des exemples fictifs, sans données réseau réelles, certificats, secrets, journaux ni historique de conversation. Les rapports expirent après 90 jours et sont supprimés chaque heure. Un marqueur d’IP de sortie dérivé avec une clé et les heures d’acceptation sont stockés séparément pour le quota des dernières 24 heures ; les entrées expirées sont nettoyées chaque heure. Ils ne figurent ni dans les rapports ni dans les logs. Supprimer un rapport ne restitue pas le quota. Les sauvegardes de récupération D1 peuvent conserver les données supprimées jusqu’à 30 jours supplémentaires. Demandez la suppression par courriel au responsable avec votre reçu. Les rapports ne sont pas publiés automatiquement.",
} as const;
