export const feedbackCopy = {
  title: "Feedback facoltativo degli agenti",
  availability: "{{name}} è un’operazione di supporto MCP facoltativa, disabilitata per impostazione predefinita. Usala solo se elencata da tools/list. Invia un rapporto privato per revisione umana; sito web, Web API e CLI non offrono l’invio.",
  authorization: "Invia solo su richiesta o con l’autorizzazione dell’utente. Un rapporto fornito o già approvato può essere inviato direttamente. Mostra prima ogni testo nuovo per l’approvazione. Non allegare conversazioni e non chiedere feedback dopo ogni chiamata.",
  inputs: "category: bug, confusing_behavior o feature_request. summary è obbligatorio; tool_name e synthetic_reproduction sono facoltativi. Un bug richiede expected e actual; un comportamento poco chiaro, actual. Una richiesta di funzionalità ammette expected, ma non actual né error_code. summary: {{summaryLimit}} punti di codice Unicode; expected/actual: {{descriptionLimit}} ciascuno; riproduzione: {{reproductionLimit}}. error_code facoltativo usa maiuscole. Campi sconosciuti rifiutati; argomenti serializzati limitati a 8 KiB.",
  limits: "Ogni IP di uscita osservato può inviare {{ipLimit}} rapporti accettati nelle ultime 24 ore. Le uscite condivise condividono la quota. Si applicano anche {{dailyLimit}} rapporti per giorno UTC e {{reportLimit}} rapporti memorizzati. Calcoli e ricerche restano indipendenti.",
  delivery: "Il successo restituisce accepted e receipt_id, senza promettere risposta o correzione. Un rifiuto certo restituisce delivery: not_accepted. Non riprovare automaticamente dopo timeout, annullamento o DELIVERY_UNCERTAIN: il rapporto potrebbe essere già salvato. Non è prevista deduplicazione.",
  privacyTitle: "Feedback volontario degli agenti",
  privacyBody: "Quando abilitato, submit-feedback salva il rapporto autorizzato e la versione pubblica del servizio in una coda privata Cloudflare D1 per revisione umana. Usa esempi sintetici; escludi dati di rete reali, certificati, segreti, log e conversazioni. I rapporti scadono dopo 90 giorni e vengono eliminati ogni ora. Un indicatore dell’IP di uscita derivato con una chiave e gli orari di accettazione sono salvati separatamente per la quota delle ultime 24 ore; le voci scadute vengono pulite ogni ora. Non compaiono nei rapporti né nei log. Eliminare un rapporto non restituisce quota. Le copie di recupero D1 possono conservare materiale eliminato per altri 30 giorni al massimo. Richiedi la cancellazione al responsabile via email con la ricevuta. I rapporti non vengono pubblicati automaticamente.",
} as const;
