export const feedbackCopy = {
  title: "Feedback facoltativo degli agenti",
  availability: "{{name}} è un’operazione facoltativa di supporto MCP, disattivata per impostazione predefinita. Usala solo quando tools/list la propone. Invia un rapporto privato per e-mail al responsabile per revisione umana; sito web, Web API e CLI non consentono invii.",
  authorization: "Invia solo su richiesta o con l’autorizzazione dell’utente. Un rapporto fornito o già approvato può essere inviato direttamente. Mostra prima ogni testo nuovo per l’approvazione. Non allegare conversazioni e non chiedere feedback dopo ogni chiamata.",
  inputs: "category: bug, confusing_behavior o feature_request. summary è obbligatorio; tool_name e synthetic_reproduction sono facoltativi. Un bug richiede expected e actual; un comportamento poco chiaro, actual. Una richiesta di funzionalità ammette expected, ma non actual né error_code. summary: {{summaryLimit}} punti di codice Unicode; expected/actual: {{descriptionLimit}} ciascuno; riproduzione: {{reproductionLimit}}. error_code facoltativo usa maiuscole. Campi sconosciuti rifiutati; argomenti serializzati limitati a 8 KiB.",
  limits: "I limiti approssimativi sono {{ipLimit}} invii per IP di uscita osservato nelle ultime 24 ore e {{dailyLimit}} per giorno UTC per l’intero servizio. Le uscite condivise condividono la quota. Richieste simultanee e propagazione KV possono superare entrambi i limiti. Invii incerti o rilasci della quota non riusciti occupano quota fino alla scadenza. Calcoli e ricerche restano indipendenti.",
  delivery: "accepted e receipt_id indicano che il servizio e-mail ha accettato l’invio, non che sia arrivato nella posta in arrivo o sia stato letto. Non si promettono risposte o correzioni. Un rifiuto confermato restituisce delivery: not_accepted. Non reinviare mai automaticamente dopo timeout, annullamento o DELIVERY_UNCERTAIN: il rapporto potrebbe essere già stato inviato per e-mail. Non è prevista deduplicazione.",
  privacyTitle: "Feedback volontario degli agenti",
  privacyBody: "Quando attivo, submit-feedback invia il rapporto autorizzato, la ricevuta, la versione pubblica del servizio e l’orario di invio tramite e-mail con Cloudflare al responsabile per revisione umana. Usa esempi sintetici; escludi dati reali di rete, certificati, segreti, registri e cronologia delle conversazioni. Conservazione ed eliminazione nella casella e-mail sono gestite manualmente; i rapporti non scadono automaticamente. Cloudflare Workers KV conserva separatamente solo marcatori dell’IP di uscita derivati con una chiave e orari di prenotazione, che scadono dopo 24 ore, senza contenuto dei rapporti o collegamenti alle ricevute. I marcatori non vengono allegati ai rapporti né registrati nei log. Eliminare un’e-mail non ripristina la quota. Richiedi l’eliminazione via e-mail al responsabile con la ricevuta. I rapporti non vengono pubblicati automaticamente.",
} as const;
