export const feedbackCopy = {
  title: "Feedback opcional de agentes",
  availability: "{{name}} é uma operação opcional de suporte MCP, desativada por padrão. Use apenas quando tools/list a anunciar. Ela envia um relato privado por e-mail ao responsável para revisão humana; site, Web API e CLI não oferecem envio.",
  authorization: "Envie somente a pedido ou com autorização do usuário. Um relato fornecido ou já aprovado pode ser enviado diretamente. Mostre qualquer texto novo para aprovação primeiro. Não anexe conversas nem solicite feedback após cada chamada.",
  inputs: "category: bug, confusing_behavior ou feature_request. summary é obrigatório; tool_name e synthetic_reproduction são opcionais. Bugs exigem expected e actual; comportamento confuso exige actual. Pedidos de recurso permitem expected, mas não actual nem error_code. summary: {{summaryLimit}} pontos de código Unicode; expected/actual: {{descriptionLimit}} cada; reprodução: {{reproductionLimit}}. error_code opcional usa maiúsculas. Campos desconhecidos são rejeitados; argumentos serializados devem caber em 8 KiB.",
  limits: "Os limites aproximados são {{ipLimit}} envios por IP de saída observado nas últimas 24 horas e {{dailyLimit}} por dia UTC para todo o serviço. Saídas compartilhadas dividem a cota. Solicitações simultâneas e a propagação do KV podem ultrapassar ambos os limites. Envios incertos ou liberações de cota que falham ocupam cota até expirar. Os cálculos e consultas não são afetados.",
  delivery: "accepted e receipt_id indicam que o serviço de e-mail aceitou o envio, sem garantir chegada à caixa de entrada ou leitura. Não há promessa de resposta ou correção. Uma rejeição confirmada retorna delivery: not_accepted. Nunca reenvie automaticamente após tempo esgotado, cancelamento ou DELIVERY_UNCERTAIN: o relato pode já ter sido enviado por e-mail. Não há deduplicação.",
  privacyTitle: "Feedback voluntário de agentes",
  privacyBody: "Quando ativado, submit-feedback envia o relato autorizado, o recibo, a versão pública do serviço e o horário de envio por e-mail através da Cloudflare ao responsável para revisão humana. Use exemplos sintéticos; exclua dados reais de rede, certificados, segredos, registros e histórico de conversas. A retenção e a exclusão na caixa de e-mail são gerenciadas manualmente; os relatos não expiram automaticamente. O Cloudflare Workers KV armazena separadamente apenas marcadores de IP de saída derivados com chave e horários de reserva, que expiram após 24 horas, sem conteúdo de relatos nem vínculos com recibos. Os marcadores não são anexados aos relatos nem registrados em logs. Excluir um e-mail não restaura a cota. Solicite a exclusão por e-mail ao responsável com o recibo. Os relatos não são publicados automaticamente.",
} as const;
