export const feedbackCopy = {
  title: "Feedback opcional de agentes",
  availability: "{{name}} é uma operação de suporte MCP opcional, desativada por padrão. Use apenas quando aparecer em tools/list. Ela envia um relato privado para análise humana; site, Web API e CLI não oferecem esse envio.",
  authorization: "Envie somente a pedido ou com autorização do usuário. Um relato fornecido ou já aprovado pode ser enviado diretamente. Mostre qualquer texto novo para aprovação primeiro. Não anexe conversas nem solicite feedback após cada chamada.",
  inputs: "category: bug, confusing_behavior ou feature_request. summary é obrigatório; tool_name e synthetic_reproduction são opcionais. Bugs exigem expected e actual; comportamento confuso exige actual. Pedidos de recurso permitem expected, mas não actual nem error_code. summary: {{summaryLimit}} pontos de código Unicode; expected/actual: {{descriptionLimit}} cada; reprodução: {{reproductionLimit}}. error_code opcional usa maiúsculas. Campos desconhecidos são rejeitados; argumentos serializados devem caber em 8 KiB.",
  limits: "Cada IP de saída observado permite {{ipLimit}} relatos aceitos nas últimas 24 horas. Saídas compartilhadas dividem a cota. Há também limites de {{dailyLimit}} relatos por dia UTC e {{reportLimit}} relatos armazenados. Os limites não afetam cálculos nem consultas.",
  delivery: "O sucesso retorna accepted e receipt_id, sem promessa de resposta ou correção. Rejeição confirmada retorna delivery: not_accepted. Não repita automaticamente após timeout, cancelamento ou DELIVERY_UNCERTAIN: o relato pode estar salvo. Não há deduplicação.",
  privacyTitle: "Feedback voluntário de agentes",
  privacyBody: "Quando ativado, submit-feedback armazena o relato autorizado e a versão pública do serviço em uma fila privada Cloudflare D1 para análise humana. Use exemplos sintéticos; exclua dados de rede reais, certificados, segredos, logs e histórico de conversa. Os relatos expiram após 90 dias e são excluídos a cada hora. Um marcador do IP de saída derivado com chave e os horários de aceitação são armazenados separadamente para a cota das últimas 24 horas; registros vencidos são limpos a cada hora. Não são anexados aos relatos nem enviados aos logs. Excluir um relato não devolve a cota. Backups de recuperação D1 podem reter material excluído por até mais 30 dias. Solicite a exclusão por email ao responsável, informando o recibo. Os relatos não são publicados automaticamente.",
} as const;
