import { PUBLIC_API_ORIGIN, MCP_PATH } from '../packages/contracts/src/index';
import { getMcpGuide } from '../apps/web/src/mcp-guide';
import { pagePaths } from '../apps/web/src/i18n/routes';
import { WEBSITE_ORIGIN } from '../apps/web/src/i18n/page-metadata';

function text(value: string) {
  return value.replace(/<code>(.*?)<\/code>/g, '`$1`');
}

function code(language: string, value: string) {
  return `\`\`\`${language}\n${value}\n\`\`\``;
}

export function createMcpGuideMarkdown() {
  const guide = getMcpGuide('en', new URL(MCP_PATH, PUBLIC_API_ORIGIN).href);
  const parts = [
    '<!-- Generated by pnpm docs:mcp:generate. Edit apps/web/src/mcp-guide.ts and the shared language resources instead. -->',
    `# ${guide.title}`, guide.explanation, guide.connection, code('text', guide.serverUrl),
    `[${guide.labels.website}](${WEBSITE_ORIGIN}${pagePaths.mcp}) · [${guide.labels.api}](${WEBSITE_ORIGIN}${pagePaths.api}) · [${guide.labels.source}](https://github.com/euyuil/packetrove)`,
    `## ${guide.connectTitle}`, guide.connectDescription,
  ];
  for (const client of guide.clients) {
    parts.push(`### ${client.name}`, code('sh', client.command), `[${client.label}](${client.url})`);
  }
  parts.push(text(guide.check), guide.discovery);
  for (const tool of guide.tools) {
    parts.push(`## ${tool.title}`, tool.purpose,
      `${guide.labels.toolName}: \`${tool.example.name}\``,
      `${guide.labels.serverAddress}: \`${guide.serverUrl}\``, tool.inputs,
      `### ${guide.labels.arguments}`, code('json', JSON.stringify(tool.example.arguments, null, 2)),
      `### ${guide.labels.exampleResult}`, code('json', JSON.stringify(tool.example.result, null, 2)),
      tool.result, tool.boundary);
    if (tool.expansion) parts.push(tool.expansion);
    parts.push(`[${tool.openTool}](${WEBSITE_ORIGIN}${pagePaths[tool.tool]})`);
  }
  parts.push(`## ${guide.errorsTitle}`, text(guide.results), text(guide.errors), guide.httpErrors,
    `## ${guide.sdk.title}`, text(guide.sdk.description), code('js', guide.sdk.code), code('sh', guide.sdk.command), text(guide.sdk.local),
    `## ${guide.deployment.title}`, ...guide.deployment.paragraphs.map(text),
    `[${guide.deployment.label}](../deployment.md)`);
  return parts.join('\n\n') + '\n';
}
