import { PUBLIC_API_ORIGIN, MCP_PATH } from '../packages/contracts/src/index';
import { getMcpGuide } from '../apps/web/src/mcp-guide';
import { pagePaths } from '../apps/web/src/i18n/routes';
import { WEBSITE_ORIGIN } from '../apps/web/src/i18n/page-metadata';
import { en } from '../apps/web/src/i18n/translations/en';

function text(value: string) {
  return value.replace(/<code>(.*?)<\/code>/g, '`$1`');
}

function code(language: string, value: string) {
  return `\`\`\`${language}\n${value}\n\`\`\``;
}

export function createMcpGuideMarkdown(productVersion?: string) {
  const guide = getMcpGuide('en', new URL(MCP_PATH, PUBLIC_API_ORIGIN).href, productVersion, en);
  const parts = [
    '<!-- Generated by pnpm docs:mcp:generate. Edit apps/web/src/mcp-guide.ts, the shared language resources, or the English verification notes in scripts/mcp-guide-markdown.ts instead. -->',
    `# ${guide.title}`, guide.explanation, guide.connection, code('text', guide.serverUrl),
    `[${guide.labels.website}](${WEBSITE_ORIGIN}${pagePaths.mcp}) · [${guide.labels.api}](${WEBSITE_ORIGIN}${pagePaths.api}) · [${guide.labels.source}](https://github.com/euyuil/packetrove)`,
    `## ${guide.connectTitle}`, guide.connectDescription,
  ];
  for (const client of guide.clients) {
    parts.push(`### ${client.name}`, code('sh', client.command), `[${client.label}](${client.url})`);
  }
  parts.push(text(guide.check), guide.discovery);
  parts.push(`## ${guide.identity.title}`, guide.identity.explanation,
    code('json', JSON.stringify(guide.identity.metadata, null, 2)), guide.identity.presentation);
  for (const tool of guide.tools) {
    parts.push(`## ${tool.title}`, tool.purpose,
      `${guide.labels.toolName}: \`${tool.example.name}\``,
      `${guide.labels.serverAddress}: \`${guide.serverUrl}\``, tool.inputs,
      `### ${guide.labels.arguments}`, code('json', JSON.stringify(tool.example.arguments, null, 2)),
      `### ${guide.labels.exampleResult}`, code('json', JSON.stringify(tool.example.result, null, 2)),
      `### ${guide.labels.resourceLink}`, code('json', JSON.stringify(tool.resourceLink, null, 2)),
      tool.result, tool.boundary);
    if (tool.exampleNote) parts.push(tool.exampleNote);
    parts.push(`[${tool.openTool}](${WEBSITE_ORIGIN}${pagePaths[tool.tool]})`);
  }
  parts.push(`## ${guide.errorsTitle}`, text(guide.results), text(guide.resultLinks), text(guide.errors), guide.httpErrors,
    `## ${guide.sdk.title}`, text(guide.sdk.description), code('js', guide.sdk.code), code('sh', guide.sdk.command), text(guide.sdk.local),
    `## ${guide.deployment.title}`, ...guide.deployment.paragraphs.map(text),
    `[${guide.deployment.label}](../deployment.md)`,
    `[${guide.deployment.privacyLabel}](${WEBSITE_ORIGIN}${pagePaths.privacy})`,
    `[${guide.deployment.registryLabel}](../cli-publishing.md#publish-to-the-official-mcp-registry)`);
  parts.push('## Client presentation check',
    'The following server-identity checks were performed on 2026-10-03 against a local feature build reporting service version 0.2.0. These observations describe the listed surfaces, not a promise about other client versions or interfaces.',
    '| Client and version | Checked surface | Observed presentation |\n'
      + '| --- | --- | --- |\n'
      + '| Codex CLI 0.160.0 | `/mcp` and `/mcp verbose` | Connected and discovered four tools. Displayed the local configuration name, connection status, tool count, and tool names; did not display the advertised server title, release version, description, website, or PNG icon. |\n'
      + '| Claude Code 2.1.288 | `claude mcp get` using a temporary isolated configuration | Connected. Displayed the local configuration name, scope, status, transport, and endpoint URL; did not display the advertised server title, release version, description, website, or PNG icon on this surface. Its interactive `/mcp` view was not checked because the isolated client stopped at account login. |',
    'The current `@modelcontextprotocol/client@2.0.0` and legacy `@modelcontextprotocol/sdk@1.30.0` integration tests separately verify complete serialized identity, discovery, exact tool results, and compatibility when optional identity fields are ignored. SDK acceptance does not establish visual rendering. No model prompt or new account authorization was used for the server-identity checks above or the app-server probes below.',
    'Further result-link observations from 2026-10-03 are recorded in the [discovery story](../user-stories/004-ai-tool-discovery.md#result-link-compatibility-observations). Codex CLI 0.160.0 app-server connected to production service 0.3.0, discovered all four tools, and retained the complete answer and link in a documentation-address `cidr-cover` response. In a separate user-prompted Codex desktop chat, the `cidr-cover` call completed, and the final answer correctly described its result and included a Markdown link using the returned tool-page URI. The desktop app version was not recorded. Native tool-card presentation, actual link opening, TUI result presentation, and Claude Code result presentation were not observed.');
  return parts.join('\n\n') + '\n';
}
